[package]
name = "kast-derive-macros"
version = "0.1.0"
edition.workspace = true
description = "derive macros for kast"
license.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = "2"
quote = "1"
proc-macro2 = "1"
