[package]
name = "kast-ast"
version = "0.1.0"
edition = "2021"
description = "ast parser for kast"
license.workspace = true
repository.workspace = true

[dependencies]
kast-util.workspace = true
tracing.workspace = true
noisy_float.workspace = true
decursion.workspace = true
