[package]
name = "kast-util"
version.workspace = true
edition.workspace = true
description = "Utilities for kast"
license.workspace = true
repository.workspace = true

[dependencies]
pad-adapter.workspace = true
thiserror.workspace = true
try-hash.workspace = true
