[package]
name = "try-hash-derive"
version = "0.1.0"
edition = "2021"
description = "Failable Hash trait (derive macros)"
license.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = "2"
quote = "1"
proc-macro2 = "1"
