[package]
name = "kast-try-hash"
version.workspace = true
edition.workspace = true
description = "Failable Hash trait"
license.workspace = true
repository.workspace = true

[dependencies]
try-hash-derive = { package = "kast-try-hash-derive", path = "derive" }
