[package]
name = "kast-try-hash"
version = "0.1.0"
edition.workspace = true
description = "Failable Hash trait"
license.workspace = true
repository.workspace = true

[dependencies]
try-hash-derive = { package = "kast-try-hash-derive", version = "0.1", path = "derive" }
