name: CI
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runs-on: ubuntu-latest
            name: linux
    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: |
          nix develop . --command just test