name: Build and test
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install and setup dune
        shell: bash
        run: |
          curl -fsSL https://get.dune.build/install | sh
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          echo "DUNE_CACHE_ROOT=$HOME/.cache/dune" >> "$GITHUB_ENV"
      - name: Cache dune’s cache
        uses: actions/cache@v4
        id: dune-cache
        with:
          path: |
            ${{ env.DUNE_CACHE_ROOT }}
          key: dune-cache-${{ runner.os }}-${{ runner.arch }}
      - name: Resolve dependencies
        shell: bash
        run: |
          dune pkg lock
      - name: Hack for linol # https://github.com/c-cube/linol/issues/57
        run: opam install linol.0.9
      - name: Build project
        shell: bash
        run: |
          dune build
      - name: Run tests
        shell: bash
        run: |
          dune runtest