name: Build and test
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5
      - name: Install Dune
        run: opam install dune
      - name: Hack for linol # https://github.com/c-cube/linol/issues/57
        run: opam install linol.0.9
      - name: Build
        run: dune build
      - name: Test
        run: dune test